/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package app.app

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class MessageUtilsTest {
    @Test
    fun sampleTest() {
        val hi = "hello world"
        assertThat(hi).contains("hello")
    }
}
